"""tabela users e normalização do banco

Revision ID: 8c27fd542746
Revises: b8bf5fa1ce87
Create Date: 2026-04-14 21:42:42.427233

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c27fd542746"
down_revision: str | Sequence[str] | None = "b8bf5fa1ce87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("category_id", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("transaction_type_id", sa.Integer(), nullable=False)
        )
        batch_op.add_column(sa.Column("bank_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_transactions_categories", "categories", ["category_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_transactions_banks", "banks", ["bank_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_transactions_users", "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_transactions_transaction_type",
            "transactions_type",
            ["transaction_type_id"],
            ["id"],
        )
        batch_op.drop_column("bank")
        batch_op.drop_column("transaction")
        batch_op.drop_column("category")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category", sa.VARCHAR(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("transaction", sa.VARCHAR(), nullable=False)
        )
        batch_op.add_column(sa.Column("bank", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(
            "fk_transactions_categories", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_transactions_banks", type_="foreignkey")
        batch_op.drop_constraint("fk_transactions_users", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_transactions_transaction_type", type_="foreignkey"
        )
        batch_op.drop_column("bank_id")
        batch_op.drop_column("transaction_type_id")
        batch_op.drop_column("category_id")
        batch_op.drop_column("user_id")

    op.drop_table("users")
    op.drop_table("transactions_type")
    op.drop_table("categories")
    op.drop_table("banks")
    # ### end Alembic commands ###
